import logging
from telegram import Update
from telegram.ext import Application, MessageHandler, filters

# Configure logging
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', 
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# Dictionary to store original messages
original_messages = {}

async def track_message_edits(update: Update, context):
    # Get the message
    message = update.message or update.edited_message
    
    if not message:
        return
    
    # Get chat ID, user, and message details
    chat_id = message.chat_id
    from_user = message.from_user
    
    # Track original message
    if not message.edit_date:
        # This is the original message
        original_messages[message.message_id] = {
            'user': from_user.username or from_user.first_name,
            'text': message.text or message.caption
        }
    else:
        # This is an edited message
        original = original_messages.get(message.message_id)
        
        if original:
            # Prepare edit notification
            edit_notification = (
                f"👤 User: {original['user']}\n"
                f"📝 Original Message: {original['text']}\n"
                f"✏️ Edited Message: {message.text or message.caption}"
            )
            
            # Send notification to your chat
            await context.bot.send_message(
                chat_id=YOUR_USER_ID,  # Replace with your actual Telegram user ID
                text=edit_notification
            )

def main():
    # Replace 'YOUR_BOT_TOKEN' with the token you provided
    application = Application.builder().token('7755934994:AAGUrrCTJ0Jwp2BBDolDazyQRIPcngN-ddQ').build()
    
    # Add message handler to track both new and edited messages
    application.add_handler(MessageHandler(
        filters.TEXT | filters.PHOTO | filters.CAPTION, 
        track_message_edits
    ))
    
    # Start the bot
    application.run_polling(drop_pending_updates=True)

if __name__ == '__main__':
    main()
